### ISSUE TITLE
imageConverter.lua returns error

### ISSUE THREAD

**Issue by ToTheMAXX** [ComputerNerd/Retro-Graphics-Toolkit#12]
I am trying to use the imageConverter.lua script in the headless examples folder. However, whenever I run the script I get an error "ImageConverter.lua:33: attempt to call a nil value (field 'loadImage')

(I realize this is a support question moreso than an issue, but I can find no other places to contact you about this project. My contact email is in my profile. Please let me know if you are still actively developing this project. Thank you!)

**Comment by ComputerNerd** [comment]
The Lua API changed but the example did not. I've updated the example to use the latest Lua API.
