### ISSUE TITLE
undeclared identifier 'htobe16' on macosx

### ISSUE THREAD

**Issue by v4ld3r5** [ComputerNerd/Retro-Graphics-Toolkit#9]
Hi,
I'm getting the following issue when compiling on macosx high sierra:

```bash
classtilemap.cpp:498:12: error: use of undeclared identifier 'htobe16'
                                                tile=htobe16(tile);//needs to be big endian
                                                     ^
..
2 warnings and 1 error generated.
make: *** [Makefile:22: classtilemap.o] Error 1
```

More details about my system:
```bash
$ xcode-select -v    
xcode-select version 2349.
 
$ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Best regards,

**Comment by v4ld3r5** [comment]
I was able to advance a bit more on my own. Implemented a new headers file with this content:
https://gist.githubusercontent.com/yinyin/2027912/raw/6b3e394dc6a37817410d66d6ba4d7cd6b8d5d03d/endian.h

And included it on the *.cpp files that complained.  It's a very dirty solution but works for now

Regards

**Comment by ComputerNerd** [comment]
I integrated the header you linked but I can't test it since I do not have an Apple computer. Please test and reply.

**Comment by ComputerNerd** [comment]
I replaced all endian code including code that uses htobe16 with code that uses Boost to handle endian conversions. Because the code no longer uses htobe16 I am closing this issue. Please try compiling the latest version when you get a chance.
